#!/bin/sh
###############################################################################
#
#    Zevenet Software License
#    This file is part of the Zevenet Load Balancer software package.
#
#    Copyright (C) 2014-today ZEVENET SL, Sevilla (Spain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

tmp_name=`/bin/date +%Y%m%d_%H%M`
hostname=`hostname`
home_dir="/usr/local/zenloadbalancer"
ss_dir="supportsave_${hostname}_${tmp_name}"
dir_backup="/tmp/${ss_dir}"
backup_to="${home_dir}/config ${home_dir}/app/zenrrd/rrd /etc/iproute2/rt_tables ${home_dir}/logs /var/log/messages* /var/log/syslog* ${home_dir}/app/cherokee/etc/cherokee/cherokee.conf /etc/ssh/sshd_config";

echo "Saving information for support in the path ${dir_backup}.tar.gz"
/bin/mkdir $dir_backup

echo "Saving loaded modules"
/sbin/lsmod > $dir_backup/lsmod.txt

echo "Saving network configuration"
/sbin/ifconfig -a >> $dir_backup/ifconfig.txt
/sbin/ip link show >> $dir_backup/ip_link.txt

echo "Saving netfilter rules"
echo "Filter table " >> $dir_backup/netfilter.txt
/sbin/iptables -nL -t filter >> $dir_backup/netfilter.txt
echo "NAT table " >> $dir_backup/netfilter.txt
/sbin/iptables -nL -t nat >> $dir_backup/netfilter.txt
echo "Mangle table " >> $dir_backup/netfilter.txt
/sbin/iptables -nL -t mangle >> $dir_backup/netfilter.txt
echo "Raw table " >> $dir_backup/netfilter.txt
/sbin/iptables -nL -t raw >> $dir_backup/netfilter.txt

echo "Saving ARP filtering"
/sbin/arptables -L > $dir_backup/arp_filtering.txt

if [ -f ${home_dir}/config/cluster.conf ]; then
	echo "Saving cluster related information"
	${home_dir}/app/zenntp/zenntp.pl > $dir_backup/ntp_test.txt 2>&1

	if [ -f ${home_dir}/node_status ];
	then
		cp ${home_dir}/node_status  $dir_backup/
		cp /etc/keepalived/keepalived.conf  $dir_backup/
		cp /etc/conntrackd/conntrackd.conf  $dir_backup/
	fi
fi

if [ -f /sbin/ipset ]; then
	echo "Saving ipset tables"
	/sbin/ipset save > $dir_backup/ipset_tables.txt 2>&1
fi

echo "Saving process status"
echo "ps aux" >> $dir_backup/ps.txt
/bin/ps aux >> $dir_backup/ps.txt

echo "Saving network status"
echo "netstat -putan" >> $dir_backup/netstat.txt
/bin/netstat -putan >> $dir_backup/netstat.txt

echo "netstat -nr" >> $dir_backup/netstat.txt
/bin/netstat -nr >> $dir_backup/netstat.txt

/usr/sbin/arp -n >> $dir_backup/arp_table.txt

/usr/sbin/dmidecode >> $dir_backup/dmi.txt
/bin/hostname >> $dir_backup/dmi.txt

/bin/cp ${home_dir}/www/*.pem $dir_backup 2>/dev/null

for i in `cat /etc/iproute2/rt_tables  | grep "table_" | awk {'print $2'}`
do
	echo "ip route list table $i" >> $dir_backup/route.txt
	/sbin/ip route list table $i >> $dir_backup/route.txt
done
echo "ip route list table main" >> $dir_backup/route.txt
/sbin/ip route list table main >> $dir_backup/route.txt
echo "ip rule list" >> $dir_backup/route.txt
/sbin/ip rule list >> $dir_backup/route.txt

echo "Capturing nf_conntrack information"
if [ -f /usr/sbin/conntrack ];
then
	/usr/sbin/conntrack -L >> $dir_backup/conntrack.txt
fi

if [ -e /proc/net/xt_recent/ ];
then
	echo "Capturing recent information"
	for file in $(ls -1 /proc/net/xt_recent/); do
		echo "Recent table for $file" >> $dir_backup/recent.txt
		cat /proc/net/xt_recent/$file >> $dir_backup/recent.txt
	done
fi

echo "Capturing system information"
echo "--- Uptime information ---" >> $dir_backup/system_resources.txt
/usr/bin/uptime >> $dir_backup/system_resources.txt
echo "--- Memory information ---" >> $dir_backup/system_resources.txt
/usr/bin/free -m >> $dir_backup/system_resources.txt
echo "--- CPU information ---" >> $dir_backup/system_resources.txt
cat /proc/cpuinfo >> $dir_backup/system_resources.txt
echo "--- TOP information ---" >> $dir_backup/system_resources.txt
/usr/bin/top -b -n1 >> $dir_backup/system_resources.txt

echo "Package list"
dpkg -l >> $dir_backup/package_list.txt

echo "Saving config and logs"
/bin/tar zcf $dir_backup/config_logs.tar.gz $backup_to 2>/dev/null
cd /tmp
/bin/tar zcf ${ss_dir}.tar.gz ${ss_dir} 2>/dev/null
cd -

/bin/rm -rf $dir_backup
