#!/usr/bin/perl

# Add this definition to the perl files to get a guarantee of good code


# install from cpan: cpan install warnings::unused
use warnings::unused;
use warnings;
use strict;

sub include { }

1;
