#!/usr/bin/perl
### BEGIN INIT INFO
# Provides:          zenloadbalancer
# Required-Start:   
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: zenloadbalancer
# Description:
#
### END INIT INFO
###############################################################################
#
#     Zen Load Balancer Software License
#     This file is part of the Zen Load Balancer software package.
#
#     Copyright (C) 2014 SOFINTEL IT ENGINEERING SL, Sevilla (Spain)
#
#     This library is free software; you can redistribute it and/or modify it
#     under the terms of the GNU Lesser General Public License as published
#     by the Free Software Foundation; either version 2.1 of the License, or 
#     (at your option) any later version.
#
#     This library is distributed in the hope that it will be useful, but 
#     WITHOUT ANY WARRANTY; without even the implied warranty of 
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
#     General Public License for more details.
#
#     You should have received a copy of the GNU Lesser General Public License
#     along with this library; if not, write to the Free Software Foundation,
#     Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
###############################################################################


$zenbin="/usr/local/zenloadbalancer/app/zbin/zenloadbalancer";
$action=$ARGV[0];

if ( "$action" eq "start"){
        my @run = `$zenbin start > /dev/console`;
        exit;
}

if ( "$action" eq "stop"){

        my @run = `$zenbin stop > /dev/console`;
        exit;
}

if ( "$action" eq "restart"){

        my @run = `$zenbin stop > /dev/console`;
        my @run = `$zenbin start > /dev/console`;
        exit;
}

if ( "$action" eq "stoplocal"){

        my @run = `$zenbin stoplocal > /dev/console`;
        exit;
}

if ( "$action" eq "startlocal"){

        my @run = `$zenbin startlocal > /dev/console`;
	my @run = `/usr/local/zenloadbalancer/app/zenlatency/zenadvrt.pl`;
        exit;
}

print "Usage: /etc/init.d/zenloadbalancer ( stop | start | restart | stoplocal | startlocal )\n";
