#!/bin/bash

LOGFILE="/usr/local/zenloadbalancer/logs/zenloadbalancer.log"
GLOBALCF="/usr/local/zenloadbalancer/config/global.conf"
GLOBALCFT="/usr/local/zenloadbalancer/app/checkglobalconf/global.conf.tpl"

[ ! "$1" == "configure" ] && echo "Installation aborted $1 $2" | tee -a $LOGFILE && exit 1
[ "$1" == "configure" ] && echo "Completing the ZLB installation..." | tee -a $LOGFILE

# Migration script
MSCRIPT="/usr/local/zenloadbalancer/app/zbin/zlbmigration302to303.pl"
if [ -f $MSCRIPT -a -f $GLOBALCF ]; then
	oldver=`cat $GLOBALCF | grep "version=" | awk -F'"' '{printf $2}'`
	newver=`cat $GLOBALCFT | grep "version=" | awk -F'"' '{printf $2}'`
	if [ "$oldver" == "3.02" ]; then
		$MSCRIPT
	fi
fi

if [ -f /usr/local/zenloadbalancer/app/zennetname/write_net_rules ]; then
	cp -f /usr/local/zenloadbalancer/app/zennetname/write_net_rules /lib/udev/
fi

# Check for binaries
PERLVER=`dpkg -l perl | grep perl | cut -d. -f-2 | xargs | cut -d\  -f3`
if [ -e "/usr/local/zenloadbalancer/www/index.cgi.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/www/index.cgi.${PERLVER}" "/usr/local/zenloadbalancer/www/index.cgi"
	rm /usr/local/zenloadbalancer/www/index.cgi.*
fi
if [ -e "/usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi.${PERLVER}" "/usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi"
	rm /usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi.*
fi
if [ -e "/usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi.${PERLVER}" "/usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi"
	rm /usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi.*
fi
if [ -e "/usr/local/zenloadbalancer/app/zbin/zenloadbalancer.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/app/zbin/zenloadbalancer.${PERLVER}" "/usr/local/zenloadbalancer/app/zbin/zenloadbalancer"
	rm /usr/local/zenloadbalancer/app/zbin/zenloadbalancer.*
fi


# GSLB user management
GSLBHOME="/var/run/gdnsd"
GSLBSHELL="/usr/sbin/nologin"
GSLBUSER="gdnsd"
GSLBGROUP="nogroup"
adduser --system -q --home $GSLBHOME --shell $GSLBSHELL --disabled-password --ingroup $GSLBGROUP $GSLBUSER

#upgrading global.conf
/usr/local/zenloadbalancer/app/checkglobalconf/checkglobalconf.cgi

# boot dependencies
sed -i 's/^\# Required-Start:.*/# Required-Start:\t\$remote_fs \$syslog zenloadbalancer/g' /etc/init.d/ssh
sed -i 's/^\# Required-Stop:.*/# Required-Stop:\t\$remote_fs \$syslog zenloadbalancer/g' /etc/init.d/ssh

#move old web server configuration
if [ -f /tmp/mini_httpd.conf ];
then
	cat /tmp/mini_httpd.conf > /usr/local/zenloadbalancer/app/mini_httpd/mini_httpd.conf
	rm -f /tmp/mini_httpd.conf
fi

if [ -d /usr/local/zenloadbalancer/app/cherokee ] && [ ! -f /tmp/cherokee.conf ]
then
	cp /usr/local/zenloadbalancer/app/cherokee/etc/cherokee/cherokee.conf /tmp/cherokee.conf
fi

if [ -f /tmp/cherokee.conf ];
then
	# Migrate if needed from minihttpd to cherokee
	if [ -f /tmp/zenport ];
	then
		ZENPORT=`cat /tmp/zenport`
		sed -i "s/^.*server!bind!1!port.*/server!bind!1!port = ${ZENPORT}/g" /tmp/cherokee.conf
		rm -f /tmp/zenport
	fi
	if [ -f /tmp/zenhost ];
	then
		ZENHOST=`cat /tmp/zenhost`
		if [ "$ZENHOST" = "*" ];
		then
			sed -i "s/^.*server!bind!1!interface.*/#server!bind!1!interface/g" /tmp/cherokee.conf
		else
			sed -i "s/^.*server!bind!1!interface.*/server!bind!1!interface = ${ZENHOST}/g" /tmp/cherokee.conf
		fi
		rm -f /tmp/zenhost
	fi
	cat /tmp/cherokee.conf > /usr/local/zenloadbalancer/app/cherokee/etc/cherokee/cherokee.conf
	rm -f /tmp/cherokee.conf
fi

# Http profile directives migration
if [ -f /usr/local/zenloadbalancer/app/zbin/zlbmigrationto402.sh ]; then
	/usr/local/zenloadbalancer/app/zbin/zlbmigrationto402.sh
fi

# Fix fwmarks for L4xNAT backends
if [ -f /usr/local/zenloadbalancer/app/zbin/fwmark_tag_fix.pl ]; then
	/usr/local/zenloadbalancer/app/zbin/fwmark_tag_fix.pl
fi

# Migrate HTTP farms to dynamic thread model, without tcmalloc
for i in $(find /usr/local/zenloadbalancer/config/ -name *pound.cfg);
do
	if [[ `grep -c ThreadModel $i` == '0' ]]; then
		echo Migrating $i
		sed -i -e 's/Threads\t\t[0-9]*$/ThreadModel\tdynamic/' $i
	fi
done

echo "Restarting Zen Load Balancer web GUI..."
if [ -f /etc/init.d/cherokee ];
then
	if [ "`pidof mini_httpd`" != "" ];
	then
		kill -9 `pidof mini_httpd`
	fi
	/etc/init.d/cherokee stop
	/etc/init.d/cherokee start
else
	/etc/init.d/minihttpd stop
	/etc/init.d/minihttpd start
fi

# restarting zenloadbalancer service
echo "ZLB will be unavailable while the service is restarting."
/etc/init.d/zenloadbalancer stop
/etc/init.d/zenloadbalancer start

###move .htpasswd from tmp to dst
if [ -f /tmp/.htpasswd ];
then
	if [ -d /usr/local/zenloadbalancer/app/cherokee/etc/cherokee ];
	then
		cat /tmp/.htpasswd > /usr/local/zenloadbalancer/app/cherokee/etc/cherokee/.htpasswd
		if [ -f /tmp/cherokee.conf ]; then
			cat /tmp/cherokee.conf /usr/local/zenloadbalancer/app/cherokee/etc/cherokee/cherokee.conf
		fi
	else
		cat /tmp/.htpasswd > /usr/local/zenloadbalancer/www/.htpasswd
	fi
	rm -f /tmp/.htpasswd
fi

# Load conntrack modules
/sbin/modprobe nf_conntrack 2> /dev/null
/sbin/modprobe ip_conntrack 2> /dev/null

# Delete manually setup ZenLB services
rm -f /etc/rc*.d/*zenloadbalancer

# Add ZenLB services to boot process including dependencies
insserv zenloadbalancer

# Link zenbui
if [ -f /usr/local/zenloadbalancer/app/zenbui/zenbui ];
then
	ln -sf /usr/local/zenloadbalancer/app/zenbui/zenbui /usr/bin/zenbui
fi

#Change prompt color
sed -i "s/1;30m/0;37m/g" /etc/bash.bashrc 2> /dev/null

#Flush apt sources
echo > /etc/apt/sources.list
( (sleep 5; /usr/bin/apt-get update) 2> /dev/null ) &

echo "Zen Load Balancer update completed..."
