#!/bin/bash

GLOBALCF="/usr/local/zenloadbalancer/config/global.conf"
GLOBALCFT="/usr/local/zenloadbalancer/app/checkglobalconf/global.conf.tpl"

[ ! "$1" == "configure" ] && echo "Installation aborted $1 $2" && exit 1
[ "$1" == "configure" ] && echo "Completing the ZLB installation..."

if [ -f /usr/local/zenloadbalancer/app/zennetname/write_net_rules ]; then
	cp -f /usr/local/zenloadbalancer/app/zennetname/write_net_rules /lib/udev/
fi

# Check for binaries
PERLVER=`dpkg -l perl | grep perl | cut -d. -f-2 | xargs | cut -d\  -f3`
if [ -e "/usr/local/zenloadbalancer/www/index.cgi.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/www/index.cgi.${PERLVER}" "/usr/local/zenloadbalancer/www/index.cgi"
	rm /usr/local/zenloadbalancer/www/index.cgi.*
fi
if [ -e "/usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi.${PERLVER}" "/usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi"
	rm /usr/local/zenloadbalancer/www/zapi/v2/zapi.cgi.*
fi
if [ -e "/usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi.${PERLVER}" "/usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi"
	rm /usr/local/zenloadbalancer/www/zapi/v1/zapi.cgi.*
fi
if [ -e "/usr/local/zenloadbalancer/app/zbin/zenloadbalancer.${PERLVER}" ]; then
	mv "/usr/local/zenloadbalancer/app/zbin/zenloadbalancer.${PERLVER}" "/usr/local/zenloadbalancer/app/zbin/zenloadbalancer"
	rm /usr/local/zenloadbalancer/app/zbin/zenloadbalancer.*
fi

# cryptolib
CRYPTOVERDEF="1.0.0"
CRYPTOVER=`find /usr/lib/ -name libcrypto.so.*.*.* | head -1 | awk -F'.' '{ printf $3 "." $4 "." $5}'`

# Check for cherokee version
CRYPTOV="$CRYPTOVER"
if [ ! -e "/usr/local/zenloadbalancer/app/cherokee.${CRYPTOV}" ]; then
	CRYPTOV="$CRYPTOVERDEF"
fi
cp -rpf /usr/local/zenloadbalancer/app/cherokee.${CRYPTOV}/* /usr/local/zenloadbalancer/app/cherokee/
rm -rf /usr/local/zenloadbalancer/app/cherokee.*

# Check for pound version
CRYPTOV="$CRYPTOVER"
if [ ! -e "/usr/local/zenloadbalancer/app/pound.${CRYPTOV}" ]; then
	CRYPTOV="$CRYPTOVERDEF"
fi
cp -rpf /usr/local/zenloadbalancer/app/pound.${CRYPTOV}/* /usr/local/zenloadbalancer/app/pound/
rm -rf /usr/local/zenloadbalancer/app/pound.*

# GSLB user management
GSLBHOME="/var/run/gdnsd"
GSLBSHELL="/usr/sbin/nologin"
GSLBUSER="gdnsd"
GSLBGROUP="nogroup"
adduser --system -q --home $GSLBHOME --shell $GSLBSHELL --disabled-password --ingroup $GSLBGROUP $GSLBUSER

#upgrading global.conf
/usr/local/zenloadbalancer/app/checkglobalconf/checkglobalconf.cgi

# Enable root access through SSH
SSHDCONFIG="/etc/ssh/sshd_config"
if [[ `grep -c "^PermitRootLogin.*yes" $SSHDCONFIG` == '0' ]]; then
	sed -i -e 's/^PermitRootLogin.*/PermitRootLogin yes/' $SSHDCONFIG
	/etc/init.d/ssh reload 2> /dev/null
fi

#Check Cherokee PID
if [ ! -f /usr/local/zenloadbalancer/app/cherokee/var/run/cherokee.pid ]; then
	pgrep cherokee$ > /usr/local/zenloadbalancer/app/cherokee/var/run/cherokee.pid
fi

# Disable services

# disable sec service
systemctl -q stop sec
systemctl -q disable sec

# disable SNMP service
if [ `grep -c '#zenlb' /etc/snmp/snmpd.conf` == '0' ]; then
        cp /usr/local/zenloadbalancer/app/checkglobalconf/snmpd.conf.tpl /etc/snmp/snmpd.conf
fi
systemctl -q stop snmpd
systemctl -q disable snmpd

# boot dependencies
sed -i 's/^\# Required-Start:.*/# Required-Start:\t\$remote_fs \$syslog zenloadbalancer/g' /etc/init.d/ssh
sed -i 's/^\# Required-Stop:.*/# Required-Stop:\t\$remote_fs \$syslog zenloadbalancer/g' /etc/init.d/ssh

# Load conntrack modules
/sbin/modprobe nf_conntrack 2> /dev/null
/sbin/modprobe ip_conntrack 2> /dev/null

# Delete manually setup ZenLB services
rm -f /etc/rc*.d/*zenloadbalancer

# Add ZenLB services to boot process including dependencies
update-rc.d zenloadbalancer defaults

# Link zenbui
if [ -f /usr/local/zenloadbalancer/app/zenbui/zenbui ];
then
	ln -sf /usr/local/zenloadbalancer/app/zenbui/zenbui /usr/bin/zenbui
fi

#Change prompt color
sed -i "s/1;30m/0;37m/g" /etc/bash.bashrc 2> /dev/null

#Flush apt sources
echo > /etc/apt/sources.list

echo "Zen Load Balancer installed..."
