#!/usr/bin/perl 

###############################################################################
#
#     This file is part of the Zen Load Balancer Enterprise Edition software
#     package.
#
#     Copyright (C) 2014 SOFINTEL IT ENGINEERING SL, Sevilla (Spain)
#     All rights reserved
#
###############################################################################

use File::Copy 'move';

my $openssl_bin   = "/usr/bin/openssl";

# Reset the sysctl in order to establish the new parameters
system ( "cp /etc/sysctl.conf /etc/sysctl.conf.bck" );
system ( qq{grep "^#" /etc/sysctl.conf > /etc/sysctl.conf 2> /dev/null} );

#Move cherokee
my $chero_conf = "/usr/local/zenloadbalancer/app/cherokee/etc/cherokee/cherokee.conf";

if ( -e  $chero_conf )
{
	move $chero_conf, "/tmp/cherokee.conf";
}

# Create the new GUI system group
system ( "groupadd -f webgui" );
system ( "usermod -a -G webgui root" );

# Create openssl DH keys
my $dhparam_certfile = "/usr/local/zenloadbalancer/app/pound/etc/dh2048.pem";

if ( ! -e $dhparam_certfile )
{
	print "Generating some SSL keys, just wait some seconds...\n";
	system ( "$openssl_bin dhparam -5 2048 -out $dhparam_certfile" );
}

exit 0;
