#!/usr/bin/perl
###############################################################################
#
#    Zevenet Software License
#    This file is part of the Zevenet Load Balancer software package.
#
#    Copyright (C) 2014-today ZEVENET SL, Sevilla (Spain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

use File::Copy 'move';

my $BM_tag = 0; # _BM_tag_

if ( ! $BM_tag )
{
	my $certerr = &certcontrol();
	if ( $certerr != 0 )
	{
		print "Your certificate key is not valid, error code $certerr\n";
		exit 1;    #Abort deploy
	}
}

# Reset the sysctl in order to establish the new parameters
system ( "cp /etc/sysctl.conf /etc/sysctl.conf.bck" );
system ( qq{grep "^#" /etc/sysctl.conf > /etc/sysctl.conf 2> /dev/null} );


# Create the new GUI system group
system ( "groupadd -f webgui" );
system ( "usermod -a -G webgui root" );

# Add capabilities for check_icmp
system( "setcap cap_net_raw=pe /usr/local/zevenet/app/libexec/check_icmp" );

exit 0;
