#!/bin/sh

DESC="Description of the service"
NAME=nftlb
DAEMON=/usr/local/sbin/nftlb
DAEMON_ARGS="-l 9 -H 127.0.0.1 -k HoLa -P 27"
NFTBIN=/usr/local/sbin/nft
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

[ -x "$DAEMON" ] || exit 0
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
	`$NFTBIN flush ruleset`
	start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
	[ "$?" != 0 ] && return 1
}

do_stop() {
	`$NFTBIN flush ruleset`
	start-stop-daemon --stop --signal 1 --quiet --remove-pidfile --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
	start)
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
		do_start
		case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
		;;

	stop)
		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
		do_stop
		case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
		;;

	status)
		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
		;;

	restart)
		log_daemon_msg "Restarting $DESC" "$NAME"
		do_stop
		case "$?" in
		0|1)
			do_start
			case "$?" in
				0) log_end_msg 0 ;;
				1) log_end_msg 1 ;;
				*) log_end_msg 1 ;;
			esac
			;;
		*)
			log_end_msg 1	;;
		esac
		;;

	*)
		echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
		exit 3
	;;
esac
