#!/bin/bash

# e2c
# This script create a commit with the last EE changes in the merge-ee branch of the community repository.
# The script uses the current content of the EE repository, it does not use the last commit.

# variables
CE_REPO="git@gitlab.zevenet.com:zevenet_team/zevenet-ce.git"
CE_BRANCH="merge-ee"

zevenet_home='usr/local/zevenet'
zevenet_lib='usr/share/perl5/Zevenet'
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
com_dir="${BASE_DIR}/CE_WORKDIR"
tmp_dir="${BASE_DIR}/TMP_CE_WORKDIR"
ce_files_dir="${BASE_DIR}/files-ce"
GLOBAL_CONF_TPL="${tmp_dir}/usr/local/zevenet/share/global.conf.template"
rsync_bin=`which rsync`

if [[ -z "$rsync_bin" ]]; then
	echo "ERROR: Please install rsync first. Thanks ;)"
	exit 1;
fi

function msg() {
	echo -e "\n#### ${1} ####\n"
}


function print_usage_and_exit() {
	echo "Usage: $(basename "$0") [options]

	Options:
	--auto-merge		Apply automatly a commit in the CE branch 'merge-ee'
	-b, --branch		choose which branch from the CE repository will be pulled"
	exit 1
}

function overwrite_globalconf_param() {
	local KEY=$1
	# excape character: /
	local VALUE="$(echo $2 | sed 's:/:\\/:g')"

	local CMD="sed -i 's/^\s*\\$"
	CMD+=$KEY
	CMD+='\s*=.*/\$'
	CMD+=$KEY
	CMD+='='
	CMD+=$VALUE
	CMD+="/' "
	CMD+=$GLOBAL_CONF_TPL

	eval $CMD
}

function delete_globalconf_param() {
	local KEY=$1

	local CMD="sed -i '/\\$"
	CMD+=$KEY
	CMD+="\s*=/d' "
	CMD+=$GLOBAL_CONF_TPL

	eval $CMD
}

while [ $# -gt 0 ]; do
	case $1 in
	"-b"|"--branch")
		  CE_BRANCH="$2"
		  shift
		;;
	"--auto-merge")
		AUTO_MERGE=1
		;;
	*)
		echo "Invalid option: $1"
		print_usage_and_exit
		;;
	esac

	shift
done


# get commit hash
EE_COMMIT=$(git log --oneline | head -1 | cut -d' ' -f1)

# Setup a clean EE environment
msg "Cleaning the EE directory..."
rm -rf $tmp_dir
mkdir $tmp_dir

msg "Copying EE files..."
$rsync_bin -a --exclude "/$(basename "$BASE_DIR")" ../* $tmp_dir/

# load files
source config

# remove EE files
msg "Removing EE files..."
for file in "${encrypted_files[@]}"; do
	rm -rf ${tmp_dir}/$file
done
for file in "${enterprise_files[@]}"; do
	rm -rf ${tmp_dir}/$file
done
# remove empty directories in lib
find ${tmp_dir}/$zevenet_lib -type d -empty -delete


# copy community files
msg "Copying CE files..."
cp -r ${ce_files_dir}/* ${tmp_dir}


# Overwrite CE global.conf parameters
overwrite_globalconf_param "nft_bin" '"/usr/sbin/nft";#update'
overwrite_globalconf_param "libexec_dir" '"/usr/lib/nagios/plugins";'
overwrite_globalconf_param "routeparams" '"";'
overwrite_globalconf_param "backupfor" '"$configdir $basedir/*.pem $confhttp $rttables $sshConf $snmpdconfig_file /etc/hostname $filedns /etc/cron.d/zevenet $applianceVersionFile";#update'
#~ overwrite_globalconf_param "recent_ip_list_tot" '"";'
#~ overwrite_globalconf_param "recent_ip_list_hash_size" '"";'
overwrite_globalconf_param "doc_v4_0" '"https://www.zevenet.com/zapidoc_ce_v4.0/";'

# Remove EE params from global.conf
delete_globalconf_param "blacklistsPath"
delete_globalconf_param "blacklistsConf"
delete_globalconf_param "blacklistsCronFile"
delete_globalconf_param "dosConf"
delete_globalconf_param "dosConfDir"
delete_globalconf_param "waf_body_size"

delete_globalconf_param "bond_config_file"
delete_globalconf_param "bonding_masters_filename"
delete_globalconf_param "bonding_mode_filename"
delete_globalconf_param "bonding_slaves_filename"
delete_globalconf_param "bonding_miimon_filename"

delete_globalconf_param "notifConfDir"
delete_globalconf_param "secTemplate"
delete_globalconf_param "syslogFile"

delete_globalconf_param "ssyncd_enabled"
delete_globalconf_param "ssyncd_bin"
delete_globalconf_param "ssyncdctl_bin"
delete_globalconf_param "ssyncd_port"

delete_globalconf_param "throughput_period"
delete_globalconf_param "throughput_enabled"

delete_globalconf_param "recent_ip_list_tot"
delete_globalconf_param "recent_ip_list_hash_size"

delete_globalconf_param "zcluster_manager"
delete_globalconf_param "ssh_copy_id"


# clone CE repository
msg "Cloning the community repository..."
rm -rf $com_dir
git clone $CE_REPO $com_dir
cd $com_dir
git fetch --all --tags --prune
git checkout $CE_BRANCH
cd ..

# clean the CE to detect if a file has been deleted
rm -rf ${com_dir}/*

# copy all EE to the CE
cp -r ${tmp_dir}/* $com_dir
rm -rf ${tmp_dir}

# apply the commit to CE
if [ $AUTO_MERGE ]; then

	# get CE commit SHA
	cd $com_dir
	LAST_CE_COMMIT=$(git log --oneline -n1 | sed -E 's/^.*Commit //' | sed -E 's/:.*$//')

	# get list of msg from last commit applied in CE to the EE HEAD
	cd $BASE_DIR
	DESCR=""

	while read -r lin ; do

		echo $lin | grep '\[CE\]' >/dev/null

		if [ $? -eq 0 ]; then
			FILTER=$(echo $lin | sed 's/\[CE\]//')
			DESCR="${DESCR}
	${FILTER}"
		fi

	done < <(git log $LAST_CE_COMMIT..HEAD)

	# does not do commit if there are not any commit for CE
	if [[ -z $DESCR ]]; then
		exit 0
	fi

	DATE=$(date +%H:%M:%S_%d/%m/%y)
	cd $com_dir

	git config user.email "devel@zevenet.com"
	git config user.name "AutoCommit"

	git add .
	git commit -m "Commit $EE_COMMIT:
$DESCR

date: $DATE"

	git push
fi

